### ISSUE TITLE
Open attachments like PDFs in-browser by default, not auto download

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/hypha#1253]
**Is your feature request related to a problem? Please describe.**
Documents uploaded to the website (such as PDFs) automatically download and open in-app (like Preview) rather than display in-browser. For example, click on "the study" link on this post: https://www.opentech.fund/news/exploring-online-media-filtering-during-2018-russian-presidential-elections/ (edit: this has been altered with a temporary workaround to open in google docs so you won't see the issue here)

**Describe the solution you'd like**
Attachments like PDFs open in-browser by default, ideally in a new tab

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- General public

**Comment by frjo** [comment]
This seems to be a Wagtail issue together with external storage like Amazon S3 that OTF use.

@Parbhat Wagtail serves documents with "Content-Type: application/octet-stream" and this makes the browser always download them instead of opening them in the browser (the default in most browsers). Any idea how to fix this? Wait for a fix in Wagtail?

**Comment by Parbhat** [comment]
@frjo This is the default Wagtail behaviour as 'Content-Disposition' header is [set](https://github.com/wagtail/wagtail/blob/e0f84389bbcd646eeb4410a3b19bcf91d336d336/wagtail/documents/views/serve.py#L67) to the attachment value. There are some open [issues](https://github.com/wagtail/wagtail/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Content-Disposition) in Wagtail to make it customizable. We can also create our custom document serve view to fix it but it seems better to wait for a fix in Wagtail.

**Comment by dmcdev1** [comment]
I think this may be fixed now; see for example https://www.opentech.fund/news/rise-digital-authoritarianism-egypt-digital-expression-arrests-2011-2019/ and the PDF attachment contained therein https://public.opentech.fund/documents/EgyptReportV06.pdf. it now opens in-browser for me.

**Comment by saoun** [comment]
Great @dmcdev1. 

@frjo or @Parbhat could you double-check on this?

**Comment by Parbhat** [comment]
Yeah, this issue is fixed now. From Wagtail [2.7](https://docs.wagtail.io/en/v2.8/releases/2.7.html#changes-to-document-serving-on-remote-storage-backends-amazon-s3-etc), documents are served by the external storage URL if used. Our project uses AWS S3, so Wagtail redirects to S3 URL after certain checks. So, while developing locally documents will open as an attachment and on our production (or other) environments, it opens in S3 URL.

Noticed one issue which is not related to this issue. The rich text editor currently does not allow `document-link`, `image` and `embed` features. Because the allowed list [setting](https://github.com/OpenTechFund/hypha/blob/ce125589100482c9ab0a6ba55ccce4ba3290f31c/hypha/settings/base.py#L412) is set to 

```
'features': [
    'bold', 'italic',
    'h1', 'h2', 'h3', 'h4', 'h5',
    'ol', 'ul',
    'link'
]
```

Looks like we should enable the [default features](https://docs.wagtail.io/en/v2.8/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field).

**Comment by frjo** [comment]
Yes, this can be closed for the resons @Parbhat give.

@Parbhat I think the reson for limiting options in the wagtail wysiwyg editor is that there are special stream fields for image, document and embed.

**Comment by Parbhat** [comment]
@frjo It is a good practice to use stream field blocks for images, document etc. But looks like we had the rich text features enabled earlier as the document in this news [URL](https://www.opentech.fund/news/rise-digital-authoritarianism-egypt-digital-expression-arrests-2011-2019/) is linked using rich text. Digging into history looks like earlier features can not be [set](https://github.com/wagtail/wagtail/commit/09f8a4f38a95f2760f38ab2f142443df93b5d8c6) in rich text settings. But from wagtail 2.0.1, it is enabled. So, when we removed Wagtail upgrades Todos, new feature list became the default https://github.com/OpenTechFund/hypha/commit/62536250a2ae05d5e10ed609a94bc04582343b9f

Looks like the content editors have not noticed it. If it is not required we can keep the other richtext field off.

**Comment by saoun** [comment]
Closing this for now if resolved
