### ISSUE TITLE
Make it possible to select which meta categories show in submission filter

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1292]

**Comment by saoun** [comment]
related to https://github.com/OpenTechFund/opentech.fund/issues/1293

**Comment by saoun** [comment]
is this within milestone too @frjo since it's related to #1293 ?

**Comment by rudietuesdays** [comment]
Hi @frjo and @saoun ! @harumhelmy and I could use some clarification on this issue.

Is the problem that new Meta Terms added to Wagtail don't seem to be appearing in the filters list when filtering submissions on the dashboard? Or do you want an admin user to be able to select which of the filters they see? (ie, show or don't show filters for Funds, Rounds, Screening, Terms, etc?)

This is the bar we're referring to, let us know if the issue is with something else:
<img width="1311" alt="Screen Shot 2020-04-13 at 2 51 40 PM" src="https://user-images.githubusercontent.com/10843135/79150210-5736d880-7d96-11ea-943b-e33b20bb16ff.png">

**Comment by frjo** [comment]
@rudietuesdays It already exist a checkbox on meta terms "filter_on_dashboard". Only when that is checked should the term show up in the table filter in your screenshot.
