### ISSUE TITLE
Create payment request  

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1380]
- [ ] Applicants and staff access 
- [ ] Link from project detail page to the new payment request page 
- [ ] Form with relevant fields
value
invoice 
receipts 
period of invoice

**Comment by fourthletter** [comment]
Applicants are currently unable to access the payment request page.

Example: https://test-apply.opentech.fund/apply/projects/8/
![image](https://user-images.githubusercontent.com/20019656/65179943-c9765300-da29-11e9-9344-e6a8967e916c.png)

**Comment by todd-dembrey** [comment]
This looks to be resolved in the sprint 3 work.

**Comment by fourthletter** [comment]
I had trouble creating a new payment request because I didn't upload up an Invoice and Receipt(s) in the **required** fields. It is not necessary to require both receipts and invoice fields because it's unlikely projects will need to submit both an invoice and receipt each time they create a new payment request. Thanks.

![image](https://user-images.githubusercontent.com/20019656/69358956-b95f3780-0c55-11ea-899e-b87979d5afcd.png)

**Comment by todd-dembrey** [comment]
The changes have been merged and deployed as part of 1.20.0 https://github.com/OpenTechFund/hypha/releases/tag/v1.20.0

@fourthletter - can you confirm the correct behaviour of this? Is it that receipts are optional when making a payment request?

**Comment by fourthletter** [comment]
@todd-dembrey - both receipts and invoice fields are still required on the test site. The behavior should give users the option to upload/attach an invoice and/or receipt. The correct behavior should not require users to utilize both fields when submitting a payment request.

I conducted the test on this project: https://test-apply.opentech.fund/apply/projects/payment-requests/16/

I was not given the option to upload ONLY the invoice or ONLY the receipt. In other words, an invoice without a receipt OR a receipt without an invoice. I was required to attach a document to both fields in order to submit a payment request.

**Comment by todd-dembrey** [comment]
I've made it optional to upload receipts to payment requests, I've deployed this to test.
