### ISSUE TITLE
Simplify Project Page 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1399]
- [x]  accessible through URL for OTF staff
- [x] Back link to project 
- [x] Styling as per normal project/submission page 
- [x] No tabs, sidebar or ability to edit 
- [x] Information shown is: 
title 
same information as the project page 
output of ticket #1364 
output review information (split into OTF review and AC review - show name and date of review) 
show approval (who and when) 
- [x] Shows a link to submission #1372  
- [x] Shows a link to all documents uploaded

**Comment by fourthletter** [comment]
Staff could edit a majority of the Approval Form that renders the Simplify Project Page. We also need to edit the "output review information (split into OTF review and AC review - show name and date of review) show approval (who and when)" because this information is mutable during the process. Thanks!

**Comment by todd-dembrey** [comment]
@fourthletter I'm unsure how the information is mutable - as we understood it the reviews have been completed by the time the project is created. 

The approvals are added to the page as they are created. Are we missing some approvals from the OTF side or are you imagining that we need to track compliance and other approvals?

Either way that is outside the scope of this ticket - we are building for a static rendering of the information, can you please create a new ticket in order to cover this?

**Comment by fourthletter** [comment]
We need the PAF to contain **only** the name and date/timestamp of reviews, not the **results/outcomes** from reviews. Compliance only requires a reviewer's name and date the review was submitted. We value reviewers' expertise, feedback, and questions to help proposals improve. Providing only the results/outcomes, e.g., "Yes" or "No" from reviews does not reflect a proposal's progress and revisions.

Example: https://test-apply.opentech.fund/apply/projects/1/simplified/

**Image shows results/outcomes next to names below:**

![image](https://user-images.githubusercontent.com/20019656/66832553-25000780-ef28-11e9-91fd-2932c18879ec.png)

**Comment by fourthletter** [comment]
The Review form currently does not contain any information even though the submission has been reviewed by two people. https://test-apply.opentech.fund/apply/projects/12/simplified/

**Comment by todd-dembrey** [comment]
Hi @fourthletter 

There are 2 reviews on the concept:
https://test-apply.opentech.fund/apply/submissions/124/
There are 0 reviews on the proposal:
https://test-apply.opentech.fund/apply/submissions/125/

The PAF is pulling through only from the Proposal and not the concept. This is perhaps not what you expected?. How should it behave?

**Comment by fourthletter** [comment]
@todd-dembrey Pulling reviewers from the proposal is the correct behavior. This issue is ready for deployment if the PAF contains only the name and date/timestamp of reviews, not the results/outcomes from reviews as I commented on Oct 15, 2019. @frjo We could deploy this issue if we can change the behavior to only include the name and date/timestamp with no other information. 

Test conducted on 4 February 2020
https://test-apply.opentech.fund/apply/projects/16/simplified/

![image](https://user-images.githubusercontent.com/20019656/73788437-08077280-476b-11ea-927b-859b1ca790d2.png)

**Comment by todd-dembrey** [comment]
This is merged and deployed - all features as expected.
