### ISSUE TITLE
Implement the Learning Lab Page by uracreative

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1739]

**Comment by AnXh3L0** [comment]
Hey @frjo, attached you'll find the assets (svg icons and text + colors). Let me know in the soonest so I can login and work on it.

[assets.zip](https://github.com/OpenTechFund/opentech.fund/files/4087301/assets.zip)

**Comment by AnXh3L0** [comment]
Here's the header background, svg is inside.

[header.zip](https://github.com/OpenTechFund/opentech.fund/files/4091145/header.zip)

**Comment by frjo** [comment]
Ready to test on test:

* https://test.opentech.fund/results/learnings/
* https://test-apply.opentech.fund/admin/pages/98/

**Comment by frjo** [comment]
@dmcdev1 ping

**Comment by AnXh3L0** [comment]
Thanks @frjo, needs some very tiny changes, otherwise it's looking good.

**Comment by dmcdev1** [comment]
@frjo it looks pretty good. only request (and let me know if this isn't possible):

- is it possible to get rid of the pixels on the right side of the header image? they're blocking some of the illustration, would be nice if they were deleted.

Otherwise I played around with the page functions (ability to link to different pages, eliminating unncessary elements, add illustrations/other text, etc) and it looks good to me.
