### ISSUE TITLE
HMW enable staff to unassign themselves from reviews?

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1855]

**Comment by fourthletter** [comment]
Related to #1575

Describe the bug
The edit reviewers modal box doesn't allow a reviewer to be removed from the list of reviewers.

To Reproduce

Go to an application with one or two reviewers assigned
Click Reviewers.
Dropdown only allows you to change reviewer to another reviewer, no option to set no one.
Expected behavior
The ability to remove a reviewer from an assigned application.

Priority

Low priority (annoying, would be nice to not see)
Affected roles

Staff
Reviewers
