### ISSUE TITLE
Change how we screen applications, make it easier

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1948]
A common need is for managers to quickly flag an application as within remit or within the scope of the open call). At its most basic, this is an "in" or an "out". Not every deployment will have a need for multiple different types of screening statuses. Here's my proposal.

* Add a required "In" or "Out" option for all screening status, "/admin/funds/screeningstatus/create/"
* Add a "Set to default" option for all screening status. 
* If no screening statuses exist, hide the option from application pages for those who don't use them.
* Replace the "screen application" button with a red down and greed up arrow (or thumbs up or down).
* On click of red icon, set status as default out status. If not default set, use the first out status created.
* On click of green icon, set status as default in status. If not default set, use the first in status created.
* On click and hold/longpress of either icon, an overlay comes on up top of only the "Actions to take" box, listing the in/out options according to the clicked icon. On click of an option sets the status. Clicking outside/away closes the overlay and does not set a status.

Any thoughts? Issues/concerns? Refinements?

cc @georgiamoon 

Assuming all good to proceed, would like to get @psycle folks cracking on this.

**Comment by danblah** [comment]
@fourthletter, how do you think this would feel for you and @OTF team during screening? Helpful, not helpful?

**Comment by georgiamoon** [comment]
Adding @bumbleblue here who's looked at the reviewer side more than me.

**Comment by fourthletter** [comment]
Particularly useful during the initial screening, this feature would enable users to segment submissions into clear buckets of work or next steps. Examples of next steps are to send a determination, review application, etc. 

Indicators like a thumbs up/star/label to mark "In" or "Out" would expedite the screening process. 

Currently, the screening process enables only one label per submission and limits to a few label options that fit within broad categories. Staff comments, within the comment/communication tab, are better indicators for how to proceed with a particular application because these comments provide nuance and substantive information. Staff comments could also be converted into ad hoc labels since there isn't an easy method to sort and group these comments.

**Comment by ei8fdb** [comment]
Hi @danblah, @fourthletter (PS: great handle :)), 

I'm picking up this ticket (and #1954). In order to start, I'd like to request:

- at best, access to an admin interface (test is fine!)
- or at least, see some screenshots of the admin interface

so I can understand it.

Is that possible?

**Comment by frjo** [comment]
@ei8fdb You are admin on https://test-apply.opentech.fund/, same e-mail as you have in Slack.

**Comment by danblah** [comment]
So bumping this... the ability to screen in/out with tags that correlate to common determination messages (reasons for moving forward or dismissing) YES PLEASE!

**Comment by danblah** [comment]
Adding that for my own purposes, I want the ability to "screen" an application as In/Out of scope (the required up/down above) and then quickly label it with other non-required statuses (ie competitive, too expensive, way outside of scope, offer a call, not applied research, not user-focused, etc).

**Comment by Parbhat** [comment]
Is anyone working on this or requirements finalised to start implementation?

**Comment by frjo** [comment]
@Parbhat No one is working on this. @ei8fdb Was going to look at the UX of it but got sidetracked by other tasks I believe.

I think staff would like this.

I think the action to see all screening options need to be more obvious than a "long press" (can that even be implemented on the web?). A smaller "Screening options" button below the thumbs or similar. @ei8fdb any input on this?

**Comment by frjo** [comment]
This need to be in the React app so an API endpoint is needed.

**Comment by Parbhat** [comment]
@frjo Thanks for the information. Looks like we need to implement it both on Submission detail and React interface.

**Comment by frjo** [comment]
@Parbhat For the actions on Submission detail it would be really good if staff can apply them without need to reload the page. The flag action already uses a crud ajax function that I built.

Something like thet but more solid and generic that uses the API for all actions is our goal in the long run.

**Comment by Parbhat** [comment]
Yeah, that will be good UX.

**Comment by sks444** [comment]
@frjo, we have added this in our todos and will soon start with the implementation.

Just to confirm: so we want two required screening statuses created by default `In` and `Out`, or default statuses for `In`/`Out` could also be set by admin.

On the application detail page, we want `Thumbs up`, `Thumbs down` to quickly set `In`/`Out` statuses respectively. Then we want to have more statuses which could be created in admin and listed/set by clicking on `Screening options` on the detail page.

Seems like this will more helpful in the react interface so we will first target to implement it there.

**Comment by frjo** [comment]
@sks444 I envision a system where staff adds any number of screening statuses.

Each status can be marked as yes or no. (in and out of remit is OTF centric I have been told so lets stick with generic yes/no)

Staff can then set one of these as default yes and one as default no.

Hitting the thumbs up/down will pick the default.

I suggest we for now copy the current UI from the Screening Status box (see below) to display just below the thumbs. Then staff can easily see the selected screening status and change it if needed.


![Skärmavbild 2020-10-20 kl  08 43 10](https://user-images.githubusercontent.com/191392/96550603-5d5fc180-12b1-11eb-9fa7-899fff6934af.png)
![Skärmavbild 2020-10-20 kl  08 41 55](https://user-images.githubusercontent.com/191392/96550616-5f298500-12b1-11eb-8e75-a57b4f1451cb.png)
![Skärmavbild 2020-10-20 kl  09 11 31](https://user-images.githubusercontent.com/191392/96552622-4cfd1600-12b4-11eb-82ed-74b84b8f6ef5.png)

**Comment by sks444** [comment]
That's understandable. Thanks @frjo.

Along with setting the default screening status with thumbs. I think we also need a way to set more statuses for yes/no.

That means one submission can have one or more screening statuses set at a time.

Seems like we would have to change our [ForeignKey](https://github.com/OpenTechFund/hypha/blob/cc1ce26347a516b199ce70ca13640acd980f51bd/hypha/apply/funds/models/submissions.py#L456) relation to ManyToMany.

**Comment by sks444** [comment]
### Implementation plan

**Moving from ManyToOne to ManyToMany:**

As now, one submission can have multiple screening statuses set, we need to move our relation from ForeignKey to ManyToMany:

- Add a new field `screening_statuses` to ApplicationSubmission model with relation `ManyToMany`.
- Migrate the old data from the field `screening_status` to new `screening_statuses` field and remove the old field.
- Use the new `screening_statuses` field in place of old [`screening_status`](https://github.com/OpenTechFund/hypha/search?p=1&q=screening_status) for filters, templates etc.

**Change in old Screening status Model:**
- Add two new fields to [ScreeningStatus](https://github.com/OpenTechFund/hypha/blob/cc1ce26347a516b199ce70ca13640acd980f51bd/hypha/apply/funds/models/screening.py#L4) model: 
   - `yes`: BooleanField: If marked use this screening status for `yes` otherwise use it for `no`.
   - `default`: BooleanField: If marked use this screening status as default `yes` or default `no`.
       - Validation: Only two screening statuses can be marked as default: one for `yes` and one for `no`.

**APIs:**
- GET: `api/v1/screening_statuses/`: List all the available screening statuses. Accept filters for `yes/no` and `default`.
- POST: `api/v1/submissions/<pk>/screening_statuses/default/`: Api to set the default screening status on a submission with `thumbs up` and `thumbs down`. Accepts data `{"yes": true/false }`.
- POST: `api/v1/submissions/<pk>/screening_statuses/`: Api to set a screening status on a submission. Accepts data: `{"screening_status": value}`
   - Validation: If the default screening status is set as `yes`, a screening status for `no` shouldn't be set. And vice versa.

**Frontend Flow:**

@vimal1083 will work on the frontend for this in react interface. So he would be able to give us more ideas about the ui when the apis are done. But here is a rough idea of how the flow should be:

- Have the screening status box.
- Get the default screening statuses from the api for `yes` and `no`. And display it with `thumbs`.
- On click `thumbs up` use the default api(`api/v1/submissions/<pk>/screening_statuses/default/`) to set the default screening status for `yes` and vice versa.
- If the default screening status is set for `yes`, show a button with `Screening options`, on click, list all available screening statuses for `yes`.
- If the default screening status is set for `no`, show a button with `Screening options`, on click, list all available screening statuses for `no`.
- On click of an option sets the status. Clicking outside/away closes the overlay and does not set a status.

@frjo, let me know your views, if there is something to add/remove.

**Comment by frjo** [comment]
@sks444 This sounds excellent!

**Comment by sks444** [comment]
@frjo, would you be open to disabling the screening feature from the Django's submission detail page? Given that all the old screening data is being used in the new flow in the react interface and at other places like filters, tables..etc.

We can not support both the old screening flow and the new one simultaneously. And implementing the new flow on submission detail page could be time consuming.

I am guessing as staff is using the react interface more and more we might not need this feature there. But if it is required we may create a separate issue or implement the new flow at both places simultaneously.

**Comment by Parbhat** [comment]
Having the feature on the submission detail page would be good. React app is getting more features but it would be good to maintain the functionality of the normal pages.

**Comment by sks444** [comment]
@Parbhat, Agree. Anyhow @vimal1083 is busy with determination frontend. So I could use that time to work on the detail page.

**Comment by frjo** [comment]
I think we need to keep the functionality on the submission detail page.

Would be great to have the action there also use the API.

**Comment by sks444** [comment]
@frjo, to migrate the old screening statuses to new one we need to know which ones are for yes/no. But we could not know that as we only had the [title field](https://github.com/OpenTechFund/hypha/blob/cc1ce26347a516b199ce70ca13640acd980f51bd/hypha/apply/funds/models/screening.py#L5) earlier. So to solve this, we are thinking to deploy the changes to [ScreeningStatus model](https://github.com/OpenTechFund/hypha/blob/c848b5a47d2567d2b8e8f7f863933cea6313bffc/hypha/apply/funds/models/screening.py#L6) first and let admins select the yes/no for existing statuses for Hypha/Reset on production/test. Then we can easily migrate and merge/deploy the new screening flow.


To give an update, we have made good progress on this. All the backend changes and the new screening statuses functionality on submission detail page has been implemented in this [pr](https://github.com/OpenTechFund/hypha/pull/2148)(I will add notes to test this out). Now only thing that remains is adding this to react interface.

**Comment by frjo** [comment]
@di @danblah Now that #2154 has been deployed can you please go to your Screening statuses and mark them yes/no and the defaults for each. You find them in Wagtail admin Apply -> Screening statuses.

This is in preparation for the migration that will be needed for the new system.
