### ISSUE TITLE
Missing migration in project

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2094]
I first thought this was linked to https://github.com/OpenTechFund/hypha/pull/2085 but now I seeing it on master with a fresh db dump from live.

Is it really missing migration, the sites deploy as they should.

```
# Generated by Django 2.2.14 on 2020-07-29 08:52

from django.db import migrations, models
import hypha.apply.projects.models
import hypha.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0034_multi_input_char_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(storage=hypha.storage_backends.PrivateMediaStorage(), upload_to=hypha.apply.projects.models.contract_path),
        ),
        migrations.AlterField(
            model_name='packetfile',
            name='document',
            field=models.FileField(storage=hypha.storage_backends.PrivateMediaStorage(), upload_to=hypha.apply.projects.models.document_path),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='file',
            field=models.FileField(storage=hypha.storage_backends.PrivateMediaStorage(), upload_to=hypha.apply.projects.models.receipt_path),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='invoice',
            field=models.FileField(storage=hypha.storage_backends.PrivateMediaStorage(), upload_to=hypha.apply.projects.models.invoice_path),
        ),
        migrations.AlterField(
            model_name='reportprivatefiles',
            name='document',
            field=models.FileField(storage=hypha.storage_backends.PrivateMediaStorage(), upload_to=hypha.apply.projects.models.report_path),
        ),
    ]

```

**Comment by Parbhat** [comment]
@frjo I think you are getting this locally because you may have set [AWS_STORAGE_BUCKET_NAME](https://github.com/OpenTechFund/hypha/blob/a1d14f94bc4a4b78506a1fb3cb8269d66b25396d/hypha/settings/base.py#L547) while testing file uploads for #2085. It changes the storage value on [FileField](https://github.com/OpenTechFund/hypha/blob/a1d14f94bc4a4b78506a1fb3cb8269d66b25396d/hypha/apply/projects/models.py#L93) as [PrivateStorage](https://github.com/OpenTechFund/hypha/blob/a1d14f94bc4a4b78506a1fb3cb8269d66b25396d/hypha/apply/utils/storage.py#L7) value is [PRIVATE_FILE_STORAGE](https://github.com/OpenTechFund/hypha/blob/a1d14f94bc4a4b78506a1fb3cb8269d66b25396d/hypha/settings/base.py#L549) when  `AWS_STORAGE_BUCKET_NAME` is set. Otherwise, it is `django.core.files.storage.FileSystemStorage()`. The change in model field triggers the migration creation as older [migrations](https://github.com/OpenTechFund/hypha/blob/a1d14f94bc4a4b78506a1fb3cb8269d66b25396d/hypha/apply/projects/migrations/0023_ensure_contracts_uses_private_storage.py#L18) has set the storage value on fields to file system storage. Looks like we do not need to make any changes. As on production files should be uploaded on S3 and locally local file storage is being used.

**Comment by frjo** [comment]
@Parbhat You are absolutely correct, unsetting AWS_STORAGE_BUCKET_NAME locally fixes the issue. Thanks for clearing this up for me!
