### ISSUE TITLE
NPM install from package.json with deleted package-lock.json and clean npm cache

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2178]
```
$ rm -rf node_modules package-lock.json
$ npm cache clean --force
$ npm install
```

Trying then to run the React app with:

$ gulp watch:app

Result in "｢wdm｣: Failed to compile."

See complete errors at https://dpaste.com/9VTXUFDZK

Reverting to the committed version of package-lock.json in master and everything works again.

My guess is that the `package.json` file needs a look at?

**Comment by vimal1083** [comment]
Hi @frjo,

Found that a dependency got missed in `package.json`, Have added it and created a [PR](https://github.com/OpenTechFund/hypha/pull/2180). 

Also I would request not to delete `package-lock.json` because this file holds the versions of all the dependencies we use in our project, if you delete this file and do a `npm install`, `npm` will install the latest version of all our dependencies. The author of the dependency might have removed/changed the functions they expose, but our application will expect the dependency to work same as in dev environment. So the app will not work sane always if we delete `package-lock.json` and install dependencies.

**Comment by frjo** [comment]
@vimal1083 Thanks for quick response! I only delete package-lock.json when I want to update node packages to fix security issues etc.

**Comment by vimal1083** [comment]
If we delete `package-lock.json` and install dependencies it will update all dependencies, application may not work. if you want to upgrade some packages to fix security issue, let me know I'll update those packages one by one.
