### ISSUE TITLE
As an applicant/manager/reviewer, ability to link to specific communication elements (comments, submission responses, email notifications, etc)

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#336]

**Comment by frjo** [comment]
@danblah You want to link to items on e.g. /apply/submissions/*/#communications?

This is currently not possible.

On a standard view it would be easy to add a id to each item and link to them with an #id.

Since this view already uses a #submission-details/#communications/#activity-feed it will conflict.
