### ISSUE TITLE
Turn browser spell check support on

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#706]

**Comment by frjo** [comment]
The WYSIWYG editor for the rich text field messes with the form and disables the browsers built in spell check. In all other forms, including the new Markdown text field, spell check works as normal.

**Comment by tmsndrs** [comment]
@frjo is there anything we can do about that?

**Comment by frjo** [comment]
Stop using the RichText widget for submissions, see 
https://github.com/OpenTechFund/opentech.fund/pull/693

**Comment by danblah** [comment]
Closing this, doesn't seem to be an issue any longer.

**Comment by georgiamoon** [comment]
This came up again in our interviews. Is there any potential solution for users that can work?

**Comment by frjo** [comment]
@georgiamoon We would need to switch to another wysiwyg editor that allow the browsers built in spelling system to work, unsure if such a thing exist.

**Comment by georgiamoon** [comment]
@frjo reviewing the thread here, it sounds like there are multiple options for editors and it's just in the RichText editor that the browser spellcheck doesn't work? is that right?

If so, then I'm wondering if there's a bug in the RichText editor where there should be some spellcheck functionality and that isn't working? Or should we think about how to better support users so that they know how to use the Markdown editor where spellcheck works?

**Comment by frjo** [comment]
Turns out TinyMCE do have a setting for allowing the browser native spell checking to work and it's by default sett to off for some reason. Do not know how I missed this in my first look in to this.

It ready for testing on the test site now.

**Comment by georgiamoon** [comment]
Woo!

**Comment by frjo** [comment]
@georgiamoon Thanks for nudging me to look in to this!

**Comment by georgiamoon** [comment]
Thank you for finding the fix!
