### ISSUE TITLE
Allow the role team to change the visibility setting for submission comments 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#944]

**Comment by fourthletter** [comment]
Relates to these closed items #1087 #945

**Comment by danblah** [comment]
See https://github.com/OpenTechFund/opentech.fund/issues/1174

**Comment by saoun** [comment]
@frjo does this mean, allow a team member to edit the visibility of a comment AFTER posting it? 

If so, can we implement this? Is it complex? Expected behavior would be:

- team posts a comment
- team has ability to 'edit' comment via edit button
- team can edit the comment itself (text) and re-save, and edit the visibility 

i can imagine something similar to slack, where there is a set limit of say 1 minute for staff to be able to edit the text and visibility option.

**Comment by frjo** [comment]
@saoun You can already edit your own comments. I believe this is about staff editing visibility on any comment, to correct mistakes. Say an applicant posted a comment but set the wrong visibility.

I have never been asked to correct a comment visibility so I do not think it's so common.

**Comment by saoun** [comment]
@frjo yes, editing works, my bad.

I do see a case for editing visibility. I've sometimes posted something as internal when i meant to do public, and then had to repost as public. And vice versa. 

If someone hits "Edit", is it possible to make the visibility editable as well as an option?

**Comment by frjo** [comment]
I will have a look at that, should not be hard to implement.

**Comment by saoun** [comment]
@frjo @harumhelmy can this be done for this Q1?

**Comment by harumhelmy** [comment]
Sorry for my delay on this! @frjo @saoun Haven't had much capacity the last couple of weeks — but should have a lot more starting this week. On this issue now.

**Comment by fourthletter** [comment]
@harumhelmy no worries! Please let us know if you have questions about any of the GitHub issues. Thank you!

**Comment by frjo** [comment]
Will be on test in a few minuts, deploying now.

**Comment by fourthletter** [comment]
Acceptance criteria visible and functional during test. Thank you! 💥
